version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    environment:
      REPO_URL: redis://redis:6379
      INSECURE: "true"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - type: volume
        source: redis-data
        target: /data
volumes:
  redis-data:
